server:
  port: 8091

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  type-aliases-package: com.yiguan.douban.entity
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    username: yiguan_club
    password: YiGuanXYZ.@()85258638
    url: jdbc:mysql://cdb-be3bjsg8.bj.tencentcdb.com:10209/douban_analysys?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
#    schema:
#      - classpath:data.sql
    initialization-mode: always
