server:
  port: 8091

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  type-aliases-package: com.yiguan.douban.entity
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    username: analysys_club
    password: YiGuanXYZ.@()85258638
    url: jdbc:mysql://118.25.133.235:3306/douban_analysys?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
#    schema:
#      - classpath:data.sql
    initialization-mode: always

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false

security:
  basic:
    enabled: false

